# Generated by Django 4.1.6 on 2023-04-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_expertprofile_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='ratingofex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
