# Generated by Django 4.1.6 on 2023-05-04 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_workdetails_address_workdetails_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
