# Generated by Django 4.1.6 on 2023-05-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_expertprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
