# Generated by Django 4.1.6 on 2023-05-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_workdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetails',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=30),
        ),
    ]
