# Generated by Django 4.2.1 on 2023-05-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_content_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='link',
        ),
        migrations.RemoveField(
            model_name='content',
            name='post_type',
        ),
    ]
