# Generated by Django 4.2.1 on 2023-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='experience',
            field=models.CharField(default='No experiences', max_length=300),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='qualification',
            field=models.CharField(default='No qualifications', max_length=300),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='ratingofex',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='workdetails',
            name='description',
            field=models.TextField(max_length=999),
        ),
    ]
