# Generated by Django 4.2.1 on 2023-05-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='ratingofex',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
