# Generated by Django 4.2.1 on 2023-05-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_expertprofile_experience_expertprofile_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='experience',
            field=models.CharField(default='No experiences yet', max_length=300),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='qualification',
            field=models.CharField(default='No experiences yet', max_length=300),
        ),
    ]
