# Generated by Django 4.2.1 on 2023-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_expertprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='experience',
            field=models.CharField(default='No experiences', max_length=300),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='qualification',
            field=models.CharField(default='No qualifications', max_length=300),
        ),
    ]
