# Generated by Django 4.2.1 on 2023-05-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_expertprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetails',
            name='description',
            field=models.TextField(max_length=999),
        ),
        migrations.RunSQL(
            "ALTER TABLE api_expertprofile ADD FULLTEXT (name)",
            "ALTER TABLE api_expertprofile DROP INDEX name",
        ),

    ]
