# Generated by Django 4.2.1 on 2023-05-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_workdetails_description'),
    ]

    operations = [
        migrations.RunSQL(
        "ALTER TABLE api_expertprofile ADD FULLTEXT (name)",
        "ALTER TABLE api_expertprofile DROP INDEX name",
    )
    ]
